# Cross Validation -- Ejemplo

## Importar librerias

In [1]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression,LinearRegression
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score

## Utilizar de manera normal los sets train y test

In [2]:
iris = load_iris()
X = iris.data
y = iris.target
print(X.shape)
print(y.shape)

(150, 4)
(150,)


In [3]:
print(X[:5]) #4 caracteristicas

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [4]:
print(y) #3 clases

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=0)
#Se usa un tamaño muy grande de test set para bajar el accuracy final, sino, sería de 1.0

In [6]:
print(X_train.shape, X_test.shape)
print(y_train.shape, y_test.shape)

(90, 4) (60, 4)
(90,) (60,)


### Regresion logistica

In [7]:
rlModel = LogisticRegression()
rlModel.fit(X_train,y_train) #Entrenamiento

LogisticRegression()

In [8]:
predict = rlModel.predict(X_test) #Pruebas con test set

In [9]:
print("Accuracy = ", accuracy_score(predict,y_test))

Accuracy =  0.9166666666666666


### Regresion Lineal

In [10]:
lrModel = LinearRegression()
lrModel.fit(X_train,y_train)
scoreLR = lrModel.score(X_test,y_test)
print("Accuracy LR = ", scoreLR)

Accuracy LR =  0.8885645804630061


## Usar Cross Validation

In [11]:
from sklearn.model_selection import cross_val_score, KFold

### Regresion Logistica

In [12]:
rlCVModel = LogisticRegression(max_iter=500)
rlCVModel.fit(X,y) #se usara todo el data set, pero usando 10 folds

LogisticRegression(max_iter=500)

### Entrenamiento con Cross Validation

In [13]:
folds = KFold(n_splits=10) #creación de los folds
score = cross_val_score(rlCVModel,X,y,cv=folds) #entrenamiento con los folds

In [14]:
print("Fold scores: ",score)
print("Mean Cross Validation score: ",score.mean())

Fold scores:  [1.         1.         1.         1.         0.93333333 0.86666667
 1.         0.86666667 0.86666667 0.93333333]
Mean Cross Validation score:  0.9466666666666667


### Regresion Lineal

In [15]:
lrCVModel = LinearRegression()
lrCVModel.fit(X,y)
foldsLR = KFold(n_splits=10) #creación de los folds
scoreLR = cross_val_score(lrCVModel,X,y,cv=foldsLR) #entrenamiento con los folds
print("Fold scores: ",scoreLR)
print("Mean Cross Validation score: ",scoreLR.mean())

Fold scores:  [0.         0.         0.         0.75710577 0.         0.
 0.84109447 0.         0.         0.        ]
Mean Cross Validation score:  0.1598200243221152
